# Generated by Django 6.0.4 on 2026-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=10)),
                ('notifications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
