# Generated by Django 6.0.4 on 2026-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
    ]
